
import java.util.ArrayList;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Srishti
 */
public class device extends javax.swing.JFrame {
static String dev_name;
static String udid;
static String version;
static String pname;
static String activity;
static String apppackage;

    /**
     * Creates new form device
     */
    public device() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        device_udid = new javax.swing.JTextField();
        device_name = new javax.swing.JTextField();
        pf_version = new javax.swing.JTextField();
        pf_name = new javax.swing.JTextField();
        app_act = new javax.swing.JTextField();
        app_pck = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(173, 181, 189));
        jLabel1.setFont(new java.awt.Font("Oswald", 1, 18)); // NOI18N
        jLabel1.setText("    ENTER  DETAILS OF DEVICE AND APP TO BE USED");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 50, 410, 40);

        device_udid.setBackground(new java.awt.Color(241, 250, 238));
        device_udid.setOpaque(true);
        device_udid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                device_udidActionPerformed(evt);
            }
        });
        getContentPane().add(device_udid);
        device_udid.setBounds(181, 378, 299, 62);

        device_name.setBackground(new java.awt.Color(241, 250, 238));
        device_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                device_nameActionPerformed(evt);
            }
        });
        getContentPane().add(device_name);
        device_name.setBounds(181, 234, 300, 62);

        pf_version.setBackground(new java.awt.Color(241, 250, 238));
        pf_version.setOpaque(true);
        pf_version.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_versionActionPerformed(evt);
            }
        });
        getContentPane().add(pf_version);
        pf_version.setBounds(181, 498, 299, 60);

        pf_name.setBackground(new java.awt.Color(241, 250, 238));
        pf_name.setOpaque(true);
        getContentPane().add(pf_name);
        pf_name.setBounds(953, 234, 310, 62);

        app_act.setBackground(new java.awt.Color(241, 250, 238));
        app_act.setOpaque(true);
        app_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                app_actActionPerformed(evt);
            }
        });
        getContentPane().add(app_act);
        app_act.setBounds(960, 490, 299, 60);

        app_pck.setBackground(new java.awt.Color(241, 250, 238));
        app_pck.setOpaque(true);
        app_pck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                app_pckActionPerformed(evt);
            }
        });
        getContentPane().add(app_pck);
        app_pck.setBounds(960, 370, 299, 60);

        jLabel2.setBackground(new java.awt.Color(173, 181, 189));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel2.setText("          UDID");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(17, 378, 120, 54);

        jLabel3.setBackground(new java.awt.Color(173, 181, 189));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel3.setText("    DEVICE NAME");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 153, 153)));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(17, 238, 118, 62);

        jLabel4.setBackground(new java.awt.Color(173, 181, 189));
        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel4.setText("      APP PACKAGE");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(750, 370, 140, 52);

        jLabel5.setBackground(new java.awt.Color(173, 181, 189));
        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel5.setText("    PLATFORM NAME");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(750, 240, 140, 52);

        jLabel6.setBackground(new java.awt.Color(173, 181, 189));
        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel6.setText(" PLATFORM VERSION ");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(17, 496, 129, 62);

        jLabel7.setBackground(new java.awt.Color(173, 181, 189));
        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel7.setText("        APP ACTIVITY");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(750, 492, 140, 50);

        jButton1.setBackground(new java.awt.Color(34, 34, 59));
        jButton1.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 255, 255));
        jButton1.setText("START");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 204, 204)));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(538, 665, 148, 62);

        jLabel8.setBackground(new java.awt.Color(213, 202, 189));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-10, 130, 1810, 1760);

        jLabel10.setBackground(new java.awt.Color(130, 111, 102));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-10, 0, 1610, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void app_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_app_actActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_app_actActionPerformed

    private void device_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_device_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_device_nameActionPerformed

    private void device_udidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_device_udidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_device_udidActionPerformed

    private void pf_versionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_versionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_versionActionPerformed

    private void app_pckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_app_pckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_app_pckActionPerformed



static public List<String> getvalues(){
List<String> values=new ArrayList<>();
values.add(dev_name);//dev_name);
values.add(udid);//udid);
values.add(version);//version);
values.add(pname);//pname);
values.add(apppackage);//apppackage);
values.add(activity);//activity);

return values;
}





    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dev_name=device_name.getText();
udid=device_udid.getText();
 version=pf_version.getText();
 pname=pf_name.getText();
 activity=app_act.getText();
apppackage=app_pck.getText();/*
 dev_name="Galaxy S10+";
udid="R38KA093V8Y";
 version="11";
 pname="Android";
 activity="com.ldt.musicr";
 apppackage="com.ldt.musicr.ui.AppActivity";*/
        // TODO add your handling code here:
//System.out.println(dev_name+udid+version+pname+activity+apppackage);
try{ setVisible(false);
HelloWorld h=new HelloWorld();}catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(device.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(device.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(device.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(device.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new device().setVisible(true);
            }   
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField app_act;
    private javax.swing.JTextField app_pck;
    private javax.swing.JTextField device_name;
    private javax.swing.JTextField device_udid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField pf_name;
    private javax.swing.JTextField pf_version;
    // End of variables declaration//GEN-END:variables
}
