/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author Srishti
 */
public class stringTrim {
    
public static void main(String args[])
{
 String pageSource="<hierarchy index=\"0\" class=\"hierarchy\" rotation=\"0\" width=\"1080\" height=\"2047\">\n" +
"  <android.widget.FrameLayout index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2047]\" displayed=\"true\">\n" +
"    <android.widget.LinearLayout index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.LinearLayout\" text=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2047]\" displayed=\"true\">\n" +
"      <android.widget.FrameLayout index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2047]\" displayed=\"true\">\n" +
"        <android.widget.LinearLayout index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.LinearLayout\" text=\"\" resource-id=\"com.ldt.musicr:id/action_bar_root\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2047]\" displayed=\"true\">\n" +
"          <android.widget.FrameLayout index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" resource-id=\"android:id/content\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2047]\" displayed=\"true\">\n" +
"            <android.view.ViewGroup index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.ViewGroup\" text=\"\" resource-id=\"com.ldt.musicr:id/appRoot\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2047]\" displayed=\"true\">\n" +
"              <android.widget.FrameLayout index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" resource-id=\"com.ldt.musicr:id/back_wall_container\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2047]\" displayed=\"true\" />\n" +
"              <android.widget.FrameLayout index=\"1\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" resource-id=\"com.ldt.musicr:id/layer_container\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2047]\" displayed=\"true\">\n" +
"                <android.widget.FrameLayout index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" resource-id=\"com.ldt.musicr:id/child_layer_container\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2047]\" displayed=\"true\">\n" +
"                  <android.widget.FrameLayout index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" resource-id=\"com.ldt.musicr:id/root\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,1874][1080,2047]\" displayed=\"true\">\n" +
"                    <android.view.ViewGroup index=\"1\" package=\"com.ldt.musicr\" class=\"android.view.ViewGroup\" text=\"\" resource-id=\"com.ldt.musicr:id/constraint_root\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,1874][1080,2047]\" displayed=\"true\">\n" +
"                      <android.view.View index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.View\" text=\"\" resource-id=\"com.ldt.musicr:id/minimize_bar\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,1874][1080,2005]\" displayed=\"true\" />\n" +
"                      <android.view.View index=\"2\" package=\"com.ldt.musicr\" class=\"android.view.View\" text=\"\" resource-id=\"com.ldt.musicr:id/divider\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,1874][1080,1877]\" displayed=\"true\" />\n" +
"                      <androidx.recyclerview.widget.RecyclerView index=\"3\" package=\"com.ldt.musicr\" class=\"androidx.recyclerview.widget.RecyclerView\" text=\"\" resource-id=\"com.ldt.musicr:id/recycler_view\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[26,1900][105,1979]\" displayed=\"true\">\n" +
"                        <android.widget.ImageView index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/image\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[26,1900][105,1979]\" displayed=\"true\" />\n" +
"                      </androidx.recyclerview.widget.RecyclerView>\n" +
"                      <android.view.ViewGroup index=\"4\" package=\"com.ldt.musicr\" class=\"android.view.ViewGroup\" text=\"\" resource-id=\"com.ldt.musicr:id/title_panel\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[131,1874][1080,2005]\" displayed=\"true\">\n" +
"                        <android.widget.TextView index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"Over the Horizon • Samsung\" resource-id=\"com.ldt.musicr:id/title\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"true\" bounds=\"[131,1892][949,1944]\" displayed=\"true\" />\n" +
"                        <android.widget.TextView index=\"1\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"play in\" resource-id=\"com.ldt.musicr:id/play_in\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[373,1949][488,1988]\" displayed=\"true\" />\n" +
"                        <android.widget.TextView index=\"2\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"All Songs\" resource-id=\"com.ldt.musicr:id/playlist_title\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[488,1949][697,1988]\" displayed=\"true\" />\n" +
"                        <android.widget.ImageView index=\"3\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/button_right\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[949,1874][1080,2005]\" displayed=\"true\" />\n" +
"                      </android.view.ViewGroup>\n" +
"                    </android.view.ViewGroup>\n" +
"                  </android.widget.FrameLayout>\n" +
"                  <android.widget.FrameLayout index=\"1\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" resource-id=\"com.ldt.musicr:id/root\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2047]\" displayed=\"true\">\n" +
"                    <android.widget.ImageView index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/back_image\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2047]\" displayed=\"true\" />\n" +
"                    <androidx.viewpager.widget.ViewPager index=\"2\" package=\"com.ldt.musicr\" class=\"androidx.viewpager.widget.ViewPager\" text=\"\" resource-id=\"com.ldt.musicr:id/view_pager\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"true\" selected=\"false\" bounds=\"[0,0][1080,2047]\" displayed=\"true\">\n" +
"                      <android.widget.FrameLayout index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" resource-id=\"com.ldt.musicr:id/container\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2047]\" displayed=\"true\">\n" +
"                        <android.widget.FrameLayout index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2047]\" displayed=\"true\">\n" +
"                          <android.view.ViewGroup index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.ViewGroup\" text=\"\" resource-id=\"com.ldt.musicr:id/UILayer\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,2047]\" displayed=\"true\">\n" +
"                            <android.view.View index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.View\" text=\"\" resource-id=\"com.ldt.musicr:id/back_ground_toolbar\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,0][1080,265]\" displayed=\"true\" />\n" +
"                            <android.widget.ImageView index=\"2\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/menu\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[32,107][190,265]\" displayed=\"true\" />\n" +
"                            <android.widget.TextView index=\"3\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"Feature\" resource-id=\"android:id/text1\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[190,107][483,265]\" displayed=\"true\" />\n" +
"                            <android.widget.ImageView index=\"4\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/list_type\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[749,113][854,260]\" displayed=\"true\" />\n" +
"                            <android.widget.ImageView index=\"5\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/search\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[854,113][1080,260]\" displayed=\"true\" />\n" +
"                            <android.view.ViewGroup index=\"6\" package=\"com.ldt.musicr\" class=\"android.view.ViewGroup\" text=\"\" resource-id=\"com.ldt.musicr:id/springBackLayout\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,265][1080,2047]\" displayed=\"true\">\n" +
"                              <android.view.ViewGroup index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.ViewGroup\" text=\"\" resource-id=\"com.ldt.musicr:id/swipe_refresh\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"false\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,265][1080,2047]\" displayed=\"true\">\n" +
"                                <android.widget.ScrollView index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.ScrollView\" text=\"\" resource-id=\"com.ldt.musicr:id/scroll_view\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,265][1080,2047]\" displayed=\"true\">\n" +
"                                  <android.widget.LinearLayout index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.LinearLayout\" text=\"\" resource-id=\"com.ldt.musicr:id/main_content_linear\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,265][1080,1402]\" displayed=\"true\">\n" +
"                                    <android.view.ViewGroup index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.ViewGroup\" text=\"\" resource-id=\"com.ldt.musicr:id/playlist_frame\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,265][1080,886]\" displayed=\"true\">\n" +
"                                      <android.view.View index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.View\" text=\"\" resource-id=\"com.ldt.musicr:id/back_top_header\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,265][1080,409]\" displayed=\"true\" />\n" +
"                                      <android.widget.TextView index=\"1\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"Playlists\" resource-id=\"com.ldt.musicr:id/title\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,265][328,409]\" displayed=\"true\" />\n" +
"                                      <android.widget.TextView index=\"2\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"3\" resource-id=\"com.ldt.musicr:id/number\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[354,298][433,377]\" displayed=\"true\" />\n" +
"                                      <android.widget.TextView index=\"3\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"See All\" resource-id=\"com.ldt.musicr:id/menu_button\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[874,310][1080,364]\" displayed=\"true\" />\n" +
"                                      <androidx.recyclerview.widget.RecyclerView index=\"4\" package=\"com.ldt.musicr\" class=\"androidx.recyclerview.widget.RecyclerView\" text=\"\" resource-id=\"com.ldt.musicr:id/recycler_view\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"true\" selected=\"false\" bounds=\"[0,409][1080,886]\" displayed=\"true\">\n" +
"                                        <android.view.ViewGroup index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.ViewGroup\" text=\"\" resource-id=\"com.ldt.musicr:id/playlist_root\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[21,409][375,839]\" displayed=\"true\">\n" +
"                                          <android.view.View index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.View\" text=\"\" resource-id=\"com.ldt.musicr:id/playlist_over\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[21,409][375,839]\" displayed=\"true\" />\n" +
"                                          <android.widget.ImageView index=\"1\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/playlist_image\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[21,409][375,763]\" displayed=\"true\" />\n" +
"                                          <android.widget.TextView index=\"2\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"Last Added\" resource-id=\"com.ldt.musicr:id/playlist_title\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[21,763][375,839]\" displayed=\"true\" />\n" +
"                                        </android.view.ViewGroup>\n" +
"                                        <android.view.ViewGroup index=\"1\" package=\"com.ldt.musicr\" class=\"android.view.ViewGroup\" text=\"\" resource-id=\"com.ldt.musicr:id/playlist_root\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[375,409][729,886]\" displayed=\"true\">\n" +
"                                          <android.view.View index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.View\" text=\"\" resource-id=\"com.ldt.musicr:id/playlist_over\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[375,409][729,886]\" displayed=\"true\" />\n" +
"                                          <android.widget.ImageView index=\"1\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/playlist_image\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[375,409][729,763]\" displayed=\"true\" />\n" +
"                                          <android.widget.TextView index=\"2\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"Recently Played\" resource-id=\"com.ldt.musicr:id/playlist_title\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[375,763][729,886]\" displayed=\"true\" />\n" +
"                                        </android.view.ViewGroup>\n" +
"                                        <android.view.ViewGroup index=\"2\" package=\"com.ldt.musicr\" class=\"android.view.ViewGroup\" text=\"\" resource-id=\"com.ldt.musicr:id/playlist_root\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[729,409][1080,839]\" displayed=\"true\">\n" +
"                                          <android.view.View index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.View\" text=\"\" resource-id=\"com.ldt.musicr:id/playlist_over\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[729,409][1080,839]\" displayed=\"true\" />\n" +
"                                          <android.widget.ImageView index=\"1\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/playlist_image\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[729,409][1080,763]\" displayed=\"true\" />\n" +
"                                          <android.widget.TextView index=\"2\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"My Top Tracks\" resource-id=\"com.ldt.musicr:id/playlist_title\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[729,763][1080,839]\" displayed=\"true\" />\n" +
"                                        </android.view.ViewGroup>\n" +
"                                      </androidx.recyclerview.widget.RecyclerView>\n" +
"                                    </android.view.ViewGroup>\n" +
"                                    <android.view.ViewGroup index=\"1\" package=\"com.ldt.musicr\" class=\"android.view.ViewGroup\" text=\"\" resource-id=\"com.ldt.musicr:id/song_frame\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,886][1080,1402]\" displayed=\"true\">\n" +
"                                      <android.view.View index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.View\" text=\"\" resource-id=\"com.ldt.musicr:id/back_top_header\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,886][1080,1030]\" displayed=\"true\" />\n" +
"                                      <android.widget.TextView index=\"1\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"Songs\" resource-id=\"com.ldt.musicr:id/title\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,886][270,1030]\" displayed=\"true\" />\n" +
"                                      <android.widget.TextView index=\"2\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"1\" resource-id=\"com.ldt.musicr:id/number\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[296,919][375,998]\" displayed=\"true\" />\n" +
"                                      <android.view.View index=\"3\" package=\"com.ldt.musicr\" class=\"android.view.View\" text=\"\" resource-id=\"com.ldt.musicr:id/refresh_front\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[880,886][1080,1030]\" displayed=\"true\" />\n" +
"                                      <android.widget.ImageView index=\"4\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/refresh\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[880,886][1080,1030]\" displayed=\"true\" />\n" +
"                                      <androidx.recyclerview.widget.RecyclerView index=\"5\" package=\"com.ldt.musicr\" class=\"androidx.recyclerview.widget.RecyclerView\" text=\"\" resource-id=\"com.ldt.musicr:id/recycler_view\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,1030][1080,1224]\" displayed=\"true\">\n" +
"                                        <android.view.ViewGroup index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.ViewGroup\" text=\"\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,1030][1080,1224]\" displayed=\"true\">\n" +
"                                          <android.widget.ImageView index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/image\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[58,1059][195,1196]\" displayed=\"true\" />\n" +
"                                          <android.widget.ImageView index=\"1\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/quick_play_pause\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[58,1059][195,1196]\" displayed=\"true\" />\n" +
"                                          <android.widget.TextView index=\"2\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"Over the Horizon\" resource-id=\"com.ldt.musicr:id/title\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[227,1074][886,1128]\" displayed=\"true\" />\n" +
"                                          <android.widget.TextView index=\"3\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"Samsung\" resource-id=\"com.ldt.musicr:id/description\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[227,1128][886,1180]\" displayed=\"true\" />\n" +
"                                          <android.widget.ImageView index=\"4\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/menu_button\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[886,1030][1080,1224]\" displayed=\"true\" />\n" +
"                                        </android.view.ViewGroup>\n" +
"                                      </androidx.recyclerview.widget.RecyclerView>\n" +
"                                      <android.widget.TextView index=\"6\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"See all songs\" resource-id=\"com.ldt.musicr:id/see_all\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[79,1256][1001,1370]\" displayed=\"true\" />\n" +
"                                    </android.view.ViewGroup>\n" +
"                                  </android.widget.LinearLayout>\n" +
"                                </android.widget.ScrollView>\n" +
"                              </android.view.ViewGroup>\n" +
"                            </android.view.ViewGroup>\n" +
"                          </android.view.ViewGroup>\n" +
"                        </android.widget.FrameLayout>\n" +
"                      </android.widget.FrameLayout>\n" +
"                    </androidx.viewpager.widget.ViewPager>\n" +
"                  </android.widget.FrameLayout>\n" +
"                  <android.widget.FrameLayout index=\"2\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" resource-id=\"com.ldt.musicr:id/root\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,2005][1080,2047]\" displayed=\"true\">\n" +
"                    <android.widget.FrameLayout index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" resource-id=\"com.ldt.musicr:id/rootCardView\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,2005][1080,2047]\" displayed=\"true\">\n" +
"                      <android.view.ViewGroup index=\"1\" package=\"com.ldt.musicr\" class=\"android.view.ViewGroup\" text=\"\" resource-id=\"com.ldt.musicr:id/constraint_root\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,2005][1080,2047]\" displayed=\"true\">\n" +
"                        <android.view.View index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.View\" text=\"\" resource-id=\"com.ldt.musicr:id/minimize_bar\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,2005][1080,2047]\" displayed=\"true\" />\n" +
"                        <android.widget.ImageView index=\"1\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/shuffle_button\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[71,2028][176,2047]\" displayed=\"true\" />\n" +
"                        <android.widget.ImageView index=\"2\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/repeat_button\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[246,2028][351,2047]\" displayed=\"true\" />\n" +
"                        <android.widget.TextView index=\"3\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"All Songs\" resource-id=\"com.ldt.musicr:id/playlist_title\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"true\" bounds=\"[422,2026][595,2047]\" displayed=\"true\" />\n" +
"                        <android.widget.ImageView index=\"4\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/down\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[595,2055][658,2118]\" displayed=\"true\" />\n" +
"                        <android.widget.TextView index=\"5\" package=\"com.ldt.musicr\" class=\"android.widget.TextView\" text=\"Lyric\" resource-id=\"com.ldt.musicr:id/lyric\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[794,2042][945,2047]\" displayed=\"true\" />\n" +
"                      </android.view.ViewGroup>\n" +
"                    </android.widget.FrameLayout>\n" +
"                  </android.widget.FrameLayout>\n" +
"                </android.widget.FrameLayout>\n" +
"                <android.view.ViewGroup index=\"1\" package=\"com.ldt.musicr\" class=\"android.view.ViewGroup\" text=\"\" resource-id=\"com.ldt.musicr:id/bottom_navigation_parent\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,2004][1080,2047]\" displayed=\"true\">\n" +
"                  <android.view.View index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.View\" text=\"\" resource-id=\"com.ldt.musicr:id/divider_bottom\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[0,2004][1080,2007]\" displayed=\"true\" />\n" +
"                  <android.widget.FrameLayout index=\"1\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" resource-id=\"com.ldt.musicr:id/bottom_navigation_view\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[173,2007][908,2047]\" displayed=\"true\">\n" +
"                    <android.view.ViewGroup index=\"0\" package=\"com.ldt.musicr\" class=\"android.view.ViewGroup\" text=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[173,2007][908,2047]\" displayed=\"true\">\n" +
"                      <android.widget.FrameLayout index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" content-desc=\"Feature\" resource-id=\"com.ldt.musicr:id/navigation_feature\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"true\" bounds=\"[173,2007][418,2047]\" displayed=\"true\">\n" +
"                        <android.widget.ImageView index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/icon\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"true\" bounds=\"[258,2043][332,2047]\" displayed=\"true\" />\n" +
"                      </android.widget.FrameLayout>\n" +
"                      <android.widget.FrameLayout index=\"1\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" content-desc=\"Library\" resource-id=\"com.ldt.musicr:id/navigation_library\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[418,2007][663,2047]\" displayed=\"true\">\n" +
"                        <android.widget.ImageView index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/icon\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[503,2043][577,2047]\" displayed=\"true\" />\n" +
"                      </android.widget.FrameLayout>\n" +
"                      <android.widget.FrameLayout index=\"2\" package=\"com.ldt.musicr\" class=\"android.widget.FrameLayout\" text=\"\" content-desc=\"Settings\" resource-id=\"com.ldt.musicr:id/navigation_setting\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[663,2007][908,2047]\" displayed=\"true\">\n" +
"                        <android.widget.ImageView index=\"0\" package=\"com.ldt.musicr\" class=\"android.widget.ImageView\" text=\"\" resource-id=\"com.ldt.musicr:id/icon\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" long-clickable=\"false\" password=\"false\" scrollable=\"false\" selected=\"false\" bounds=\"[748,2043][822,2047]\" displayed=\"true\" />\n" +
"                      </android.widget.FrameLayout>\n" +
"                    </android.view.ViewGroup>\n" +
"                  </android.widget.FrameLayout>\n" +
"                </android.view.ViewGroup>\n" +
"              </android.widget.FrameLayout>\n" +
"            </android.view.ViewGroup>\n" +
"          </android.widget.FrameLayout>\n" +
"        </android.widget.LinearLayout>\n" +
"      </android.widget.FrameLayout>\n" +
"    </android.widget.LinearLayout>\n" +
"  </android.widget.FrameLayout>\n" +
"</hierarchy>";


System.out.println(pageSource);
}
}
